/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CompactTeamDto
 */
export interface CompactTeamDto {
  /**
   *
   * @type {string}
   * @memberof CompactTeamDto
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof CompactTeamDto
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof CompactTeamDto
   */
  imageUrl: string;
  /**
   *
   * @type {string}
   * @memberof CompactTeamDto
   */
  tag: string;
  /**
   *
   * @type {string}
   * @memberof CompactTeamDto
   */
  creator: string;
  /**
   *
   * @type {boolean}
   * @memberof CompactTeamDto
   */
  locked: boolean;
}

export function CompactTeamDtoFromJSON(json: any): CompactTeamDto {
  return CompactTeamDtoFromJSONTyped(json, false);
}

export function CompactTeamDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompactTeamDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    name: json["name"],
    imageUrl: json["imageUrl"],
    tag: json["tag"],
    creator: json["creator"],
    locked: json["locked"]
  };
}

export function CompactTeamDtoToJSON(value?: CompactTeamDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    name: value.name,
    imageUrl: value.imageUrl,
    tag: value.tag,
    creator: value.creator,
    locked: value.locked
  };
}
