/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateTeamDto
 */
export interface CreateTeamDto {
  /**
   *
   * @type {string}
   * @memberof CreateTeamDto
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof CreateTeamDto
   */
  tag: string;
  /**
   *
   * @type {string}
   * @memberof CreateTeamDto
   */
  imageUrl: string;
}

export function CreateTeamDtoFromJSON(json: any): CreateTeamDto {
  return CreateTeamDtoFromJSONTyped(json, false);
}

export function CreateTeamDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTeamDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: json["name"],
    tag: json["tag"],
    imageUrl: json["imageUrl"]
  };
}

export function CreateTeamDtoToJSON(value?: CreateTeamDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    tag: value.tag,
    imageUrl: value.imageUrl
  };
}
