/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface EditTeamDto
 */
export interface EditTeamDto {
  /**
   *
   * @type {string}
   * @memberof EditTeamDto
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof EditTeamDto
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof EditTeamDto
   */
  tag?: string;
  /**
   *
   * @type {string}
   * @memberof EditTeamDto
   */
  imageUrl?: string;
}

export function EditTeamDtoFromJSON(json: any): EditTeamDto {
  return EditTeamDtoFromJSONTyped(json, false);
}

export function EditTeamDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditTeamDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    name: !exists(json, "name") ? undefined : json["name"],
    tag: !exists(json, "tag") ? undefined : json["tag"],
    imageUrl: !exists(json, "imageUrl") ? undefined : json["imageUrl"]
  };
}

export function EditTeamDtoToJSON(value?: EditTeamDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    name: value.name,
    tag: value.tag,
    imageUrl: value.imageUrl
  };
}
