/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface MatchInfoDto
 */
export interface MatchInfoDto {
  /**
   *
   * @type {string}
   * @memberof MatchInfoDto
   */
  mode: MatchInfoDtoModeEnum;
  /**
   *
   * @type {string}
   * @memberof MatchInfoDto
   */
  roomId: string;
  /**
   *
   * @type {Array<string>}
   * @memberof MatchInfoDto
   */
  radiant: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof MatchInfoDto
   */
  dire: Array<string>;
  /**
   *
   * @type {number}
   * @memberof MatchInfoDto
   */
  averageMMR: number;
  /**
   *
   * @type {string}
   * @memberof MatchInfoDto
   */
  version: MatchInfoDtoVersionEnum;
}

export function MatchInfoDtoFromJSON(json: any): MatchInfoDto {
  return MatchInfoDtoFromJSONTyped(json, false);
}

export function MatchInfoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchInfoDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    mode: json["mode"],
    roomId: json["roomId"],
    radiant: json["radiant"],
    dire: json["dire"],
    averageMMR: json["averageMMR"],
    version: json["version"]
  };
}

export function MatchInfoDtoToJSON(value?: MatchInfoDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    mode: value.mode,
    roomId: value.roomId,
    radiant: value.radiant,
    dire: value.dire,
    averageMMR: value.averageMMR,
    version: value.version
  };
}

/**
 * @export
 * @enum {string}
 */
export enum MatchInfoDtoModeEnum {
  RANKED = "RANKED",
  UNRANKED = "UNRANKED",
  SOLOMID = "SOLOMID",
  DIRETIDE = "DIRETIDE",
  GREEVILING = "GREEVILING",
  ABILITYDRAFT = "ABILITY_DRAFT",
  TOURNAMENT = "TOURNAMENT",
  BOTS = "BOTS",
  HIGHROOM = "HIGHROOM"
}
/**
 * @export
 * @enum {string}
 */
export enum MatchInfoDtoVersionEnum {
  Dota681 = "Dota_681"
}
