/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MatchmakingModeStatusEntity
 */
export interface MatchmakingModeStatusEntity {
    /**
     *
     * @type {string}
     * @memberof MatchmakingModeStatusEntity
     */
    mode: MatchmakingModeStatusEntityModeEnum;
    /**
     *
     * @type {string}
     * @memberof MatchmakingModeStatusEntity
     */
    version: MatchmakingModeStatusEntityVersionEnum;
    /**
     *
     * @type {boolean}
     * @memberof MatchmakingModeStatusEntity
     */
    enabled: boolean;
}

export function MatchmakingModeStatusEntityFromJSON(json: any): MatchmakingModeStatusEntity {
    return MatchmakingModeStatusEntityFromJSONTyped(json, false);
}

export function MatchmakingModeStatusEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchmakingModeStatusEntity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'mode': json['mode'],
        'version': json['version'],
        'enabled': json['enabled'],
    };
}

export function MatchmakingModeStatusEntityToJSON(value?: MatchmakingModeStatusEntity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'mode': value.mode,
        'version': value.version,
        'enabled': value.enabled,
    };
}

/**
* @export
* @enum {string}
*/
export enum MatchmakingModeStatusEntityModeEnum {
    RANKED = 'RANKED',
    UNRANKED = 'UNRANKED',
    SOLOMID = 'SOLOMID',
    DIRETIDE = 'DIRETIDE',
    GREEVILING = 'GREEVILING',
    ABILITYDRAFT = 'ABILITY_DRAFT',
    TOURNAMENT = 'TOURNAMENT',
    BOTS = 'BOTS',
    HIGHROOM = 'HIGHROOM',
    TOURNAMENTSOLOMID = 'TOURNAMENT_SOLOMID',
    CAPTAINSMODE = 'CAPTAINS_MODE'
}
/**
* @export
* @enum {string}
*/
export enum MatchmakingModeStatusEntityVersionEnum {
    _681 = 'Dota_681',
    _684 = 'Dota_684'
}


