/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ScheduleTournamentMatchDto
 */
export interface ScheduleTournamentMatchDto {
  /**
   *
   * @type {number}
   * @memberof ScheduleTournamentMatchDto
   */
  scheduledDate: number;
}

export function ScheduleTournamentMatchDtoFromJSON(json: any): ScheduleTournamentMatchDto {
  return ScheduleTournamentMatchDtoFromJSONTyped(json, false);
}

export function ScheduleTournamentMatchDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ScheduleTournamentMatchDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    scheduledDate: json["scheduledDate"]
  };
}

export function ScheduleTournamentMatchDtoToJSON(value?: ScheduleTournamentMatchDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    scheduledDate: value.scheduledDate
  };
}
