/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  SeedItemDto,
  SeedItemDtoFromJSON,
  SeedItemDtoFromJSONTyped,
  SeedItemDtoToJSON,
  TournamentMatchGameDto,
  TournamentMatchGameDtoFromJSON,
  TournamentMatchGameDtoFromJSONTyped,
  TournamentMatchGameDtoToJSON
} from "./";

/**
 *
 * @export
 * @interface SeedDto
 */
export interface SeedDto {
  /**
   *
   * @type {Array<SeedItemDto>}
   * @memberof SeedDto
   */
  teams: Array<SeedItemDto>;
  /**
   *
   * @type {number}
   * @memberof SeedDto
   */
  id: number;
  /**
   *
   * @type {Array<TournamentMatchGameDto>}
   * @memberof SeedDto
   */
  games: Array<TournamentMatchGameDto>;
}

export function SeedDtoFromJSON(json: any): SeedDto {
  return SeedDtoFromJSONTyped(json, false);
}

export function SeedDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeedDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    teams: (json["teams"] as Array<any>).map(SeedItemDtoFromJSON),
    id: json["id"],
    games: (json["games"] as Array<any>).map(TournamentMatchGameDtoFromJSON)
  };
}

export function SeedDtoToJSON(value?: SeedDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    teams: (value.teams as Array<any>).map(SeedItemDtoToJSON),
    id: value.id,
    games: (value.games as Array<any>).map(TournamentMatchGameDtoToJSON)
  };
}
