/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import { SeedItemDto, SeedItemDtoFromJSON, SeedItemDtoFromJSONTyped, SeedItemDtoToJSON } from "./";

/**
 *
 * @export
 * @interface SeedDto
 */
export interface SeedDto {
  /**
   *
   * @type {Array<SeedItemDto>}
   * @memberof SeedDto
   */
  teams: Array<SeedItemDto>;
  /**
   *
   * @type {string}
   * @memberof SeedDto
   */
  date: string;
  /**
   *
   * @type {number}
   * @memberof SeedDto
   */
  id: number;
  /**
   *
   * @type {number}
   * @memberof SeedDto
   */
  matchId?: number;
}

export function SeedDtoFromJSON(json: any): SeedDto {
  return SeedDtoFromJSONTyped(json, false);
}

export function SeedDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeedDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    teams: (json["teams"] as Array<any>).map(SeedItemDtoFromJSON),
    date: json["date"],
    id: json["id"],
    matchId: !exists(json, "matchId") ? undefined : json["matchId"]
  };
}

export function SeedDtoToJSON(value?: SeedDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    teams: (value.teams as Array<any>).map(SeedItemDtoToJSON),
    date: value.date,
    id: value.id,
    matchId: value.matchId
  };
}
