/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  PlayerPreviewDto,
  PlayerPreviewDtoFromJSON,
  PlayerPreviewDtoFromJSONTyped,
  PlayerPreviewDtoToJSON,
  TeamDto,
  TeamDtoFromJSON,
  TeamDtoFromJSONTyped,
  TeamDtoToJSON
} from "./";

/**
 *
 * @export
 * @interface SeedItemDto
 */
export interface SeedItemDto {
  /**
   *
   * @type {PlayerPreviewDto}
   * @memberof SeedItemDto
   */
  profile?: PlayerPreviewDto;
  /**
   *
   * @type {TeamDto}
   * @memberof SeedItemDto
   */
  team?: TeamDto;
  /**
   *
   * @type {boolean}
   * @memberof SeedItemDto
   */
  isTeam: boolean;
  /**
   *
   * @type {string}
   * @memberof SeedItemDto
   */
  result?: string;
  /**
   *
   * @type {boolean}
   * @memberof SeedItemDto
   */
  tbd?: boolean;
}

export function SeedItemDtoFromJSON(json: any): SeedItemDto {
  return SeedItemDtoFromJSONTyped(json, false);
}

export function SeedItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeedItemDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    profile: !exists(json, "profile") ? undefined : PlayerPreviewDtoFromJSON(json["profile"]),
    team: !exists(json, "team") ? undefined : TeamDtoFromJSON(json["team"]),
    isTeam: json["isTeam"],
    result: !exists(json, "result") ? undefined : json["result"],
    tbd: !exists(json, "tbd") ? undefined : json["tbd"]
  };
}

export function SeedItemDtoToJSON(value?: SeedItemDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    profile: PlayerPreviewDtoToJSON(value.profile),
    team: TeamDtoToJSON(value.team),
    isTeam: value.isTeam,
    result: value.result,
    tbd: value.tbd
  };
}
