/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface StartTournamentDto
 */
export interface StartTournamentDto {
  /**
   *
   * @type {number}
   * @memberof StartTournamentDto
   */
  id: number;
}

export function StartTournamentDtoFromJSON(json: any): StartTournamentDto {
  return StartTournamentDtoFromJSONTyped(json, false);
}

export function StartTournamentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartTournamentDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"]
  };
}

export function StartTournamentDtoToJSON(value?: StartTournamentDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id
  };
}
