/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SubmitInviteDto
 */
export interface SubmitInviteDto {
  /**
   *
   * @type {boolean}
   * @memberof SubmitInviteDto
   */
  accept: boolean;
}

export function SubmitInviteDtoFromJSON(json: any): SubmitInviteDto {
  return SubmitInviteDtoFromJSONTyped(json, false);
}

export function SubmitInviteDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmitInviteDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    accept: json["accept"]
  };
}

export function SubmitInviteDtoToJSON(value?: SubmitInviteDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    accept: value.accept
  };
}
