/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import { CompactTeamDto, CompactTeamDtoFromJSON, CompactTeamDtoFromJSONTyped, CompactTeamDtoToJSON } from "./";

/**
 *
 * @export
 * @interface TeamInvitationDto
 */
export interface TeamInvitationDto {
  /**
   *
   * @type {CompactTeamDto}
   * @memberof TeamInvitationDto
   */
  team: CompactTeamDto;
  /**
   *
   * @type {number}
   * @memberof TeamInvitationDto
   */
  inviteId: number;
}

export function TeamInvitationDtoFromJSON(json: any): TeamInvitationDto {
  return TeamInvitationDtoFromJSONTyped(json, false);
}

export function TeamInvitationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamInvitationDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    team: CompactTeamDtoFromJSON(json["team"]),
    inviteId: json["inviteId"]
  };
}

export function TeamInvitationDtoToJSON(value?: TeamInvitationDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    team: CompactTeamDtoToJSON(value.team),
    inviteId: value.inviteId
  };
}
