/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface TeamMemberDto
 */
export interface TeamMemberDto {
  /**
   *
   * @type {string}
   * @memberof TeamMemberDto
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof TeamMemberDto
   */
  steamId: string;
  /**
   *
   * @type {string}
   * @memberof TeamMemberDto
   */
  avatar: string;
}

export function TeamMemberDtoFromJSON(json: any): TeamMemberDto {
  return TeamMemberDtoFromJSONTyped(json, false);
}

export function TeamMemberDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamMemberDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: json["name"],
    steamId: json["steam_id"],
    avatar: json["avatar"]
  };
}

export function TeamMemberDtoToJSON(value?: TeamMemberDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    steam_id: value.steamId,
    avatar: value.avatar
  };
}
