/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import { TeamMemberDto, TeamMemberDtoFromJSON, TeamMemberDtoFromJSONTyped, TeamMemberDtoToJSON } from "./";

/**
 *
 * @export
 * @interface TeamDto
 */
export interface TeamDto {
  /**
   *
   * @type {string}
   * @memberof TeamDto
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof TeamDto
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof TeamDto
   */
  imageUrl: string;
  /**
   *
   * @type {string}
   * @memberof TeamDto
   */
  tag: string;
  /**
   *
   * @type {Array<TeamMemberDto>}
   * @memberof TeamDto
   */
  members: Array<TeamMemberDto>;
  /**
   *
   * @type {string}
   * @memberof TeamDto
   */
  creator: string;
}

export function TeamDtoFromJSON(json: any): TeamDto {
  return TeamDtoFromJSONTyped(json, false);
}

export function TeamDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    name: json["name"],
    imageUrl: json["imageUrl"],
    tag: json["tag"],
    members: (json["members"] as Array<any>).map(TeamMemberDtoFromJSON),
    creator: json["creator"]
  };
}

export function TeamDtoToJSON(value?: TeamDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    name: value.name,
    imageUrl: value.imageUrl,
    tag: value.tag,
    members: (value.members as Array<any>).map(TeamMemberDtoToJSON),
    creator: value.creator
  };
}
