/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface TournamentMatchGameDto
 */
export interface TournamentMatchGameDto {
  /**
   *
   * @type {number}
   * @memberof TournamentMatchGameDto
   */
  gameId: number;
  /**
   *
   * @type {number}
   * @memberof TournamentMatchGameDto
   */
  bracketMatchId: number;
  /**
   *
   * @type {number}
   * @memberof TournamentMatchGameDto
   */
  matchId?: number;
  /**
   *
   * @type {number}
   * @memberof TournamentMatchGameDto
   */
  scheduledDate: number;
  /**
   *
   * @type {number}
   * @memberof TournamentMatchGameDto
   */
  teamOffset: number;
  /**
   *
   * @type {number}
   * @memberof TournamentMatchGameDto
   */
  number: number;
}

export function TournamentMatchGameDtoFromJSON(json: any): TournamentMatchGameDto {
  return TournamentMatchGameDtoFromJSONTyped(json, false);
}

export function TournamentMatchGameDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TournamentMatchGameDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    gameId: json["gameId"],
    bracketMatchId: json["bracketMatchId"],
    matchId: !exists(json, "matchId") ? undefined : json["matchId"],
    scheduledDate: json["scheduledDate"],
    teamOffset: json["teamOffset"],
    number: json["number"]
  };
}

export function TournamentMatchGameDtoToJSON(value?: TournamentMatchGameDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    gameId: value.gameId,
    bracketMatchId: value.bracketMatchId,
    matchId: value.matchId,
    scheduledDate: value.scheduledDate,
    teamOffset: value.teamOffset,
    number: value.number
  };
}
