/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  PlayerPreviewDto,
  PlayerPreviewDtoFromJSON,
  PlayerPreviewDtoFromJSONTyped,
  PlayerPreviewDtoToJSON,
  TeamDto,
  TeamDtoFromJSON,
  TeamDtoFromJSONTyped,
  TeamDtoToJSON
} from "./";

/**
 *
 * @export
 * @interface TournamentParticipantDto
 */
export interface TournamentParticipantDto {
  /**
   *
   * @type {PlayerPreviewDto}
   * @memberof TournamentParticipantDto
   */
  profile?: PlayerPreviewDto;
  /**
   *
   * @type {TeamDto}
   * @memberof TournamentParticipantDto
   */
  team?: TeamDto;
}

export function TournamentParticipantDtoFromJSON(json: any): TournamentParticipantDto {
  return TournamentParticipantDtoFromJSONTyped(json, false);
}

export function TournamentParticipantDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): TournamentParticipantDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    profile: !exists(json, "profile") ? undefined : PlayerPreviewDtoFromJSON(json["profile"]),
    team: !exists(json, "team") ? undefined : TeamDtoFromJSON(json["team"])
  };
}

export function TournamentParticipantDtoToJSON(value?: TournamentParticipantDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    profile: PlayerPreviewDtoToJSON(value.profile),
    team: TeamDtoToJSON(value.team)
  };
}
