/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UpdateRolesDto
 */
export interface UpdateRolesDto {
  /**
   *
   * @type {string}
   * @memberof UpdateRolesDto
   */
  steamId: string;
  /**
   *
   * @type {Array<string>}
   * @memberof UpdateRolesDto
   */
  roles: Array<UpdateRolesDtoRolesEnum>;
}

export function UpdateRolesDtoFromJSON(json: any): UpdateRolesDto {
  return UpdateRolesDtoFromJSONTyped(json, false);
}

export function UpdateRolesDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateRolesDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    steamId: json["steam_id"],
    roles: json["roles"]
  };
}

export function UpdateRolesDtoToJSON(value?: UpdateRolesDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    steam_id: value.steamId,
    roles: value.roles
  };
}

/**
 * @export
 * @enum {string}
 */
export enum UpdateRolesDtoRolesEnum {
  PLAYER = "PLAYER",
  OLD = "OLD",
  HUMAN = "HUMAN",
  MODERATOR = "MODERATOR",
  ADMIN = "ADMIN"
}
